language: ruby
bundler_args: --without=release doc extra
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
  - rbx-head
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-head
